#!/bin/sh

# usage: sh mk-yaml.sh <pacman group name>

packages=$(pacman -Sgq $1)
yaml=$1.yaml
test_mode=true

if ${test_mode};then
	echo "- name: '$1'"
	echo "  description: '$1 Desktop'"
	echo "  selected: false"
		echo "  hidden: false"
	echo "  packages:"
	for pkg in ${packages[@]};do
		echo "       - $pkg"
	done
	echo ""
else
	echo "- name: '$1'" > $yaml
	echo "  description: '$1 Desktop'" >> $yaml
	echo "  selected: false" >> $yaml
	echo "  hidden: false" >> $yaml
	echo "  packages:" >> $yaml
	for pkg in ${packages[@]};do
		echo "       - $pkg" >> $yaml
	done
fi
